# RoboPlan configuration file for a model with two Franka Research 3 (FR3) robots.

joint_limits:
  left_fr3_joint1:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint2:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint3:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint4:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint5:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint6:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  left_fr3_joint7:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint1:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint2:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint3:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint4:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint5:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint6:
    max_acceleration: [2.0]
    max_jerk: [10.0]
  right_fr3_joint7:
    max_acceleration: [2.0]
    max_jerk: [10.0]
