# RoboPlan configuration file for the SO-101 robot model.

joint_limits:
  shoulder_pan:
    max_acceleration: [1.0]
    max_jerk: [5.0]
  shoulder_lift:
    max_acceleration: [10]
    max_jerk: [5.0]
  elbow_flex:
    max_acceleration: [1.0]
    max_jerk: [5.0]
  wrist_flex:
    max_acceleration: [1.0]
    max_jerk: [5.0]
  wrist_roll:
    max_acceleration: [1.0]
    max_jerk: [5.0]
  gripper:
    max_acceleration: [1.0]
    max_jerk: [5.0]
